export const TOGGLE_SIDE_BAR = 'TOGGLE_SIDE_BAR';
export const UPDATE_BAGEL_AMOUNT = 'UPDATE_BAGEL_AMOUNT';
export const ADD_TO_CART = 'ADD_TO_CART';
export const FETCH_CART = 'FETCH_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const UPDATE_DIMENSIONS = 'UPDATE_DIMENSIONS';